### ISSUE TITLE
bibtex parsing issues mentioned in forum

### ISSUE THREAD

**Issue by rsdoiel** [ORCID/bibtexParseJs#11]
Hello,

Don't want to presume too much but I've been developing bibtex Parser in Go that 
compiles to JavaScript. I can easily add a compatible bibtexParse object.
If I happen to solve some of the problems in my parser mentioned in

```
http://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/6822051-bibtex-import-is-flaky
```

would be you interested in my results? I am targetting both NodeJS and Browser with the
JavaScript I'm producing.

Thanks,

Robert

**Comment by rcpeters** [comment]
If it passed our current test we wouldn't mind migrating.

**Comment by rsdoiel** [comment]
Ok, sounds like I should proceed then. I will send a pull request when I have something useful.

All the best,

Robert
