### ISSUE TITLE
bibtext-parser vs bibtexparsejs

### ISSUE THREAD

**Issue by TuningGuide** [ORCID/bibtexParseJs#12]
Could you outline whats the difference between the two repos?

**Comment by rcpeters** [comment]
We forked it and fixed several issue we were running into. Additionally we made it run in both node and the browser.

**Comment by TuningGuide** [comment]
Could you append it to the readme for others? Or did you create a pull request?

**Comment by rcpeters** [comment]
Why don't you do a pull request. Yey open source.

**Comment by TuningGuide** [comment]
Good point ^^,
