### ISSUE TITLE
Write BibTeX

### ISSUE THREAD

**Issue by white-gecko** [ORCID/bibtexParseJs#26]
This is mostly a question, which is not very related to this project.

Is it also possible to create BibTeX again from the parsed structure? Are you aware of any js library which is able to do that?

**Comment by rcpeters** [comment]
There is a toBibtex() function. But some fields or formatting of fields can be transient. https://github.com/fiduswriter/biblatex-csl-converter Keeps a shadow copy to guarantee formatting and fields. It's also a more active project. ORCID is looking to moving over to it when we have bandwidth.

@johanneswilm fyi.
