### ISSUE TITLE
Lost ability to process strings

### ISSUE THREAD

**Issue by karger** [ORCID/bibtexParseJs#5]
The original library had methods to handle @STRING declarations; they've been removed for some reason.

**Comment by rcpeters** [comment]
Mind providing an example and also which version you are referencing?

**Comment by karger** [comment]
You forked from https://github.com/mikolalysenko/bibtex-parser , right?  Look for this.string in https://github.com/mikolalysenko/bibtex-parser/blob/master/parse-bibtex.js

**Comment by rcpeters** [comment]
@karger how about providing a sample bibtex with `@STRING`?

**Comment by rcpeters** [comment]
no sample provided
